### ISSUE TITLE
Tags for recent versions?

### ISSUE THREAD

**Issue by IzzySoft** [edev80/sibcoin-wallet#3]
Could you please add tags for recent versions (at least for the last and then for future versions) and attach the APK to them again? `releases/` shows 4.40 as last one, while Manifest shows v5.18, so it looks like there's a gap :wink:

**Comment by IzzySoft** [comment]
@edev80 ^^ ??

**Comment by IzzySoft** [comment]
PS: while on it, what license does this project use?

**Comment by IzzySoft** [comment]
Ah, found the license file in the wallet dir (GPL-3.0). Still miss the latest tags (with APK), though. Any chance, @edev80 ?

**Comment by edev80** [comment]
Maybe I will do it for the next version, but not for the current one. Sorry.

**Comment by IzzySoft** [comment]
Thanks! I'd strongly recommend it :wink: Could bring your app into the official [F-Droid](https://f-droid.org) repo. Currently it [is in mine](https://apt.izzysoft.de/fdroid/index/apk/rusapps.sibcoin.wallet) – but for given reasons hopelessly outdated. So even replacing the mentioned APK by a recent one would be great.

**Comment by IzzySoft** [comment]
@edev80 I know you didn't promise, but the "next version" was released to Play Store 4 days after your comment. It didn't turn up here in `releases/`, though. Does that mean future releases will be available only from Play Store – so those not using it (because they can't or don't want to) won't ever get any updates?

**Comment by IzzySoft** [comment]
@edev80 any chance?

**Comment by IzzySoft** [comment]
As it makes absolutely no sense to keep a totally outdated version in my repo, I will remove it now. A pity that an open-source app is only available in a "closed environment" aka "walled garden" (play store) – which means to lock out those who in taking effort to get their devices as tracking free as possible deliberately keep GApps off those.

Please let me know should you change your mind, so I can possibly reinstate your app in my repo.
